const MIN_REASON_LENGTH = 7;
const MAX_REASON_LENGTH = 100;
const MIN_VALUE = 0;
const INTERVAL_30_MINUTES_IDX = 2;
const MAX_ASSESSMENT_HOURS_DURATION = 3;

export {
  MIN_REASON_LENGTH,
  MAX_REASON_LENGTH,
  MIN_VALUE,
  MAX_ASSESSMENT_HOURS_DURATION,
  INTERVAL_30_MINUTES_IDX,
};
