export const ROUTES = {
  account_verification: '/account-verification',
  reset_password: '/reset-password',
  login: '/login',
  register: '/sign-up',
  home: '/',
  sign_up: 'sign-up',
  create_appointment: '/create-appointment',
  appointment_caregiver_list: '/caregiver-list',
  profile: '/profile',
  account_details: '/account-details',
  transactions: '/transactions',
  notifications: '/notifications',
  faq: '/faq',
  caregiver_profile: '/caregiver-profile',
  adminPanel: '/admin-panel',
};
