export const HealthConcernsAndMedicalDiagnoses = [
  "Alzheimer's/Other Dementia",
  'Anxiety Disorder',
  'Arthritis, Joint Pain',
  'Cancer',
  'Cognitive Decline',
  'Depression',
  'Diabetes',
  'General Age-related Decline',
  'Hearing Loss',
  'Heart Disease, CHF',
  'Hypertension',
  'Incontinence',
  'Lung Disease, COPD',
  'Mobility Issues',
  "Parkinson's Disease",
  'Sleep Issues',
  'Vision Loss',
];
