const route = {
  auth: 'auth',
  profile: 'profile',
  user: 'user',
  reset: '/reset-password',
  signUp: '/sign-up',
  requestResetCode: '/request-reset-otp',
  verifyResetCode: '/verify-reset-otp',
  signIn: '/sign-in',
  accountCheck: '/account-check',
  uploadFile: '/uploadFile',
  certificates: '/certificates',
  workExperience: '/work-experience',
  questionnaire_activity: '/activity',
  questionnaire_capability: '/capability',
  questionnaire_diagnosis: '/diagnosis',
  appointment: '/appointment',
  caregivers: '/caregivers',
  filter: '/filter',
  timezoneJson: '/timezone/json',
  virtualAssessment: '/virtual-assessment',
  date: '/date',
  uploadAvatar: '/upload-avatar',
  changePassword: '/change-password',
  activityLog: '/activity-log',
  transactions: '/transactions',
  notifications: '/notifications',
  adminPanel: '/admin-panel',
  admins: '/admins',
  admin: '/admin',
  updatePassword: '/update-password',
};

export { route };
